# Generated by Django 4.2.4 on 2023-08-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_evento', models.TextField()),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('local_online', models.IntegerField()),
                ('faixa_estaria', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
