# Generated by Django 4.2.4 on 2023-09-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='eventos',
        ),
    ]
