# Generated by Django 4.2.4 on 2023-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_alter_evento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horario_final',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
