# Generated by Django 4.2.4 on 2023-09-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_evento_horario_final_evento_horario_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='faixa_estaria',
            new_name='faixa_etaria',
        ),
    ]
