# Generated by Django 4.2.4 on 2023-09-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_rename_faixa_estaria_evento_faixa_etaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario_final',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='horario_inicio',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
