# Generated by Django 4.2.4 on 2023-09-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_remove_evento_horario_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.TextField(default='teste'),
        ),
        migrations.AddField(
            model_name='evento',
            name='politica',
            field=models.TextField(default='teste'),
        ),
        migrations.AddField(
            model_name='evento',
            name='website',
            field=models.TextField(default='teste'),
        ),
    ]
